// src/components/MailSignup.svelte
<style>
  .email-input {
    border: none;
    border-bottom: 3px solid white;
    color: #76bc21;
  }
  .email-input:focus {
    outline: none;
    background: #222;
  }
</style>

<div class="mw7 ph3 pt5 center">
  <div class="measure lh-copy">
    <h3 class="f3">Sign up for our mailing list:</h3>
    <div class="mt3">
      <form
        action="https://steadystatecycles.us20.list-manage.com/subscribe/post?u=424770fe49cd2cba58248aff0&amp;id=b8e9ffcca3"
        method="post"
        id="mc-embedded-subscribe-form"
        name="mc-embedded-subscribe-form"
        class="validate"
        target="_blank"
        novalidate>
        <div>
          <div>
            <label class="db mb2 f4" for="mce-EMAIL">Email Address</label>
            <input
              type="email"
              value=""
              name="EMAIL"
              class="input-reset email-input bg-transparent b lh-solid pa3 w-100
              f5"
              id="mce-EMAIL" />
          </div>
          <div>
            <div
              class="response"
              id="mce-error-response"
              style="display:none" />
            <div
              class="response"
              id="mce-success-response"
              style="display:none" />
          </div>
          <div style="position: absolute; left: -5000px;" aria-hidden="true">
            <input
              type="text"
              name="b_424770fe49cd2cba58248aff0_b8e9ffcca3"
              tabindex="-1"
              value />
          </div>
          <div class="mt3">
            <input
              type="submit"
              value="Subscribe"
              name="subscribe"
              id="mc-embedded-subscribe"
              class="button-reset bg-white bw0 black b lh-solid pa3 f5" />
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

// components/MailSignup.vue
<template>
  <div class="mw7 ph3 pt5 center">
    <div class="measure lh-copy">
      <h3 class="f3">Sign up for our mailing list:</h3>
      <!-- Begin Mailchimp Signup Form -->
      <div class="mt3">
        <form
          action="https://steadystatecycles.us20.list-manage.com/subscribe/post?u=424770fe49cd2cba58248aff0&amp;id=b8e9ffcca3"
          method="post"
          id="mc-embedded-subscribe-form"
          name="mc-embedded-subscribe-form"
          class="validate"
          target="_blank"
          novalidate
        >
          <div>
            <div>
              <label class="db mb2 f4" for="mce-EMAIL">Email Address</label>
              <input
                type="email"
                value
                name="EMAIL"
                class="input-reset email-input bg-transparent b lh-solid pa3 w-100 f5"
                id="mce-EMAIL"
              >
            </div>
            <div>
              <div class="response" id="mce-error-response" style="display:none"></div>
              <div class="response" id="mce-success-response" style="display:none"></div>
            </div>
            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true">
              <input type="text" name="b_424770fe49cd2cba58248aff0_b8e9ffcca3" tabindex="-1" value>
            </div>
            <div class="mt3">
              <input
                type="submit"
                value="Subscribe"
                name="subscribe"
                id="mc-embedded-subscribe"
                class="button-reset bg-white bw0 black b lh-solid pa3 f5"
              >
            </div>
          </div>
        </form>
      </div>

      <!--End mc_embed_signup-->
    </div>
  </div>
</template>

<style scoped>
.email-input {
  border: none;
  border-bottom: 3px solid white;
  color: #76bc21;
}
.email-input:focus {
  outline: none;
  background: #222;
}
</style>
